name: 功能请求 / Feature request
description: 提出你的功能请求 / Propose your feature request
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: 功能描述
      description: 请描述你希望增加什么功能
      placeholder: 例如：希望增加方向场结果的可视化输出...
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 使用场景
      description: 这个功能解决什么问题？
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 可能的实现方式
      description: 如果你有想法，可以简单写一下
    validations:
      required: false